### PR TITLE
Lineage pull request for: skeleton

### LINKED ISSUE #48: Currently a number of tests fail because asu.edu's CDNs do not match expected values
# 🐛 Summary #

`test_grab_cdn`, `test_has_cdn`, `test_run_checks_present`, and `test_cname` all currently fail because ASU apparenty uses Fastly primarily now, as well as a lone file hosted on cloudflare via `unpkg.com`.

This can be verified manually, and also with [this public tool report](https://www.cdnplanet.com/tools/cdnfinder/#id:1333113234469_703372656317790a07ba).

Additionally, the DNS record for `asu.edu` shows that they are using Akamai 'akam.net' for DNS Queries, which was missing from the master list of CDN domain names. Adding this is probably a good move, since Akamai is showing up on their DNS query.

### Should this tool care about Nameserver usage? I don't know if asu.edu using Akami for DNS is even relevant to this tool, and could use some feedback there.

https://www.dnswatch.info/dns/dnslookup?la=en&host=asu.edu&type=A&submit=Resolve

It's also worth noting that "akam.net" is not on the list of recognized CDNs in the tool, and I am not sure if that is important or not.

## To reproduce ##

Run the unit tests

> pytest

## Expected behavior ##

The unit tests should pass, they do not. 

More specifically, `asu.edu` should not based on the current collection criteria return `cloudflare.net` as a CDN.

## Any helpful log output or screenshots ##

Paste the results here:

```console
E assert {'adobe.com':...udflare.com']} == {'adobe.com':...udflare.com']}
E         Omitting 2 identical items, use -vv to show
E         Differing items:
E         {'asu.edu': ['.fastly.net', '.nocookie.net']} != {'asu.edu': ['.cloudflare.net', '.cloudflare.com']}
E         Full diff:
E           {
E            'adobe.com': ['.edgesuite.net', '.akamaitechnologies.fr'],
E         -  'asu.edu': ['.cloudflare.net', '.cloudflare.com'],...
E
E         ...Full output truncated (4 lines hidden), use '-vv' to show
```

Add any screenshots of the problem here.

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by dav3r — APPROVED** [review]

**Review by jsf9k — APPROVED** [review]

**Review by jsf9k — COMMENTED** [review]
The changes look good to me, but the tests are failing.

**Comment by jsf9k** [comment]
I was told by @Yablargo that this project is heavily used and he wants to try and resolve some of the existing issues; hence, I am updating this Lineage PR.

**Comment by jsf9k** [comment]
Resolves #48.

**Review by jsf9k — APPROVED** [review]

**Comment by S4lt5** [comment]
~I think the issue to link is  #18 which covers the exec() use which is no longer included in the newest version of the skeleton., #48 is not related, as far as I can tell.~

This should fix #48, however I think the question about nameserver records still should be explored, but I can open a fresh issue with just that.

**Review by dav3r — APPROVED** [review]
LGTM! 👍

**Comment by jsf9k** [comment]
Foiled!  A review from @mcdonnnj or @Pascal-0x90 is required due to the `CODEOWNERS` file.

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔

**Pull request merged**
